# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schemas/compose-spec.json
services:
  minio:
    image: minio/minio:latest
    container_name: rfp-tool-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - rfp-network

volumes:
  minio_data:
    driver: local

networks:
  rfp-network:
    driver: bridge

